# Generated by Django 5.1.5 on 2025-01-27 07:58

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_transactions.category')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='Комментарий к записи')),
                ('amount', models.PositiveIntegerField(help_text='Количество средств в рублях.')),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_transactions.category')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_transactions.status')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_transactions.subcategory')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_transactions.transactiontype')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='transaction_types',
            field=models.ManyToManyField(to='financial_transactions.transactiontype'),
        ),
        migrations.AddConstraint(
            model_name='subcategory',
            constraint=models.UniqueConstraint(fields=('name', 'category'), name='unique_subcategory'),
        ),
    ]
